[package]
name = "cloudflare-ddns-service"
version = "0.4.0"
authors = ["Jan Christian Grünhage <jan.christian@gruenhage.xyz>"]
edition = "2018"
description = "A daemon to use Cloudflare as a DDNS provider"
repository = "https://git.jcg.re/jcgruenhage/cloudflare-ddns-service"
homepage = "https://git.jcg.re/jcgruenhage/cloudflare-ddns-service"
keywords = ["cloudflare", "ddns"]
categories = ["command-line-utilities"]
license-file = "LICENSE"
documentation = "https://git.jcg.re/jcgruenhage/cloudflare-ddns-service"
readme = "README.md"

[dependencies]
reqwest= { version = "0.11.13", features = ["blocking", "json"] }
serde = { version = "1.0.152", features = ["derive"] }
anyhow = "1.0.68"
env_logger = "0.10.0"
log = "0.4.17"
tokio = { version = "1.23.0", features = ["time", "macros", "rt-multi-thread"] }
serde_yaml = "0.9.16"
cloudflare = "0.10.1"
